/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl_sql.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl_sql.ui.internal.Mydsl_sqlActivator;

public class SQLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl_sqlActivator.getInstance().getInjector("org.xtext.example.mydsl_sql.SQL");
	}

}
