/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl_sql.sQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl_sql.sQL.Model#getWq <em>Wq</em>}</li>
 *   <li>{@link org.xtext.example.mydsl_sql.sQL.Model#getQuery <em>Query</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl_sql.sQL.SQLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Wq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wq</em>' containment reference.
   * @see #setWq(WithQuery)
   * @see org.xtext.example.mydsl_sql.sQL.SQLPackage#getModel_Wq()
   * @model containment="true"
   * @generated
   */
  WithQuery getWq();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl_sql.sQL.Model#getWq <em>Wq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wq</em>' containment reference.
   * @see #getWq()
   * @generated
   */
  void setWq(WithQuery value);

  /**
   * Returns the value of the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' containment reference.
   * @see #setQuery(SelectQuery)
   * @see org.xtext.example.mydsl_sql.sQL.SQLPackage#getModel_Query()
   * @model containment="true"
   * @generated
   */
  SelectQuery getQuery();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl_sql.sQL.Model#getQuery <em>Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query</em>' containment reference.
   * @see #getQuery()
   * @generated
   */
  void setQuery(SelectQuery value);

} // Model
