/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl_sql.sQL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl_sql.sQL.Model#getSimpleStatement <em>Simple Statement</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl_sql.sQL.SQLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Statement</em>' containment reference.
   * @see #setSimpleStatement(SimpleStatement)
   * @see org.xtext.example.mydsl_sql.sQL.SQLPackage#getModel_SimpleStatement()
   * @model containment="true"
   * @generated
   */
  SimpleStatement getSimpleStatement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl_sql.sQL.Model#getSimpleStatement <em>Simple Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple Statement</em>' containment reference.
   * @see #getSimpleStatement()
   * @generated
   */
  void setSimpleStatement(SimpleStatement value);

} // Model
