/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl_sql.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl_sql.SQLRuntimeModule;
import org.xtext.example.mydsl_sql.SQLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SQLIdeSetup extends SQLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SQLRuntimeModule(), new SQLIdeModule()));
	}
	
}
